imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
  dbal:
      host: db
      port: 3306
      dbname: test_application
      user: root

security:

    providers:
        in_memory:
            memory:
                users:
                    lengoo_test:
                        password: $2y$12$JH7NcT4JXy1s8GpwEVR2suECw/msPGZgarj2QJqIRwUxoUPUpYnnu
                        roles: 'ROLE_ADMIN'

