security:

    providers:
        in_memory:
            memory:
                users:
                    lengoo:
                        password: $2y$12$qeqpHdAlTOkfBS9NIU.pl.GjvNsNbdQdAjETti/8R6vHy/WtE9b52
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~

    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
            Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt
                cost: 12

