application_homepage:
    path:     /
    defaults: { _controller: ApplicationBundle:Default:index }

ApplicationBundle_default_create:
    path:  /apply/
    defaults: {  _controller: ApplicationBundle:Default:create}
    requirements:
        methods:  POST
ApplicationBundle_default_admin:
    path:  /admin/
    defaults: {  _controller: ApplicationBundle:Default:admin}
ApplicationBundle_default_login:
    path: /login/
    defaults: {  _controller: ApplicationBundle:Default:login}
ApplicationBundle_default_logout:
    path: /logout/
ApplicationBundle_default_download:
    path: /download/{id}
    defaults: { _controller: ApplicationBundle:Default:download }
    requirements:
        methods:  GET
        id: \d+

