application_homepage:
    path:     /
    defaults: { _controller: ApplicationBundle:Default:index }

ApplicationBundle_default_create:
    path:  /apply/
    defaults: {  _controller: ApplicationBundle:Default:create}
    requirements:
        methods:  POST
ApplicationBundle_default_admin:
    path:  /admin/
    defaults: {  _controller: ApplicationBundle:Default:admin}
